### ISSUE TITLE
Error when validating [...]: certificate has expired

### ISSUE THREAD

**Issue by chrisidefix** [freelan-developers/freelan#106]
I wanted to start using `freelan` again (under Mac OS X El Capitan) and installed the most recent version, which I compiled from source today. Everything is set up the same way I had used it in the past with signed certificates for every node.

Unfortunately, no connection is established and I am repeatedly seeing the following message (in the console):
```
08/03/16 19:05:09.342 freelan[69]: Error when validating [...]: certificate has expired (depth: 1)
08/03/16 19:05:09.342 freelan[69]: Ignoring PRESENTATION from [IP]:[PORT] as the signature certificate is invalid.
```

Obviously, you might think some certificates are expired, but all certificates I ever created are valid until 2025 or 2026. The only issue I see is that the timestamps inside the certificates are referring to GMT time zone, while I am now currently in a very different time zone with a 9 hour shift.

Any ideas what could cause this problem - I am not sure what I should be looking for here?

Is there any way I could "debug" the certificates and verify with OpenSSL and see what the actual problem is?

**Comment by chrisidefix** [comment]
Alright, after a quick search it turns out you can check the expiry date with:
`openssl x509 -enddate -noout -in ca.crt`

Looks like my originally created signing certificate expired only a month after I created it - no idea if this is supposed to work like that, but looks like the problem is indeed simply an expired certificate.

If anyone knows how I can fix this, don't hesitate to tell me, please.

**Comment by ereOn** [comment]
Hi @chrisidefix,

Yes indeed, the error message is pretty straightforward in this case: you'll have to create another (self-signed) certificate. You can do so using the same private key if you want to.

Usually, the steps for doing that are:

- Create a Certificate Request (`.csr` file) from your private key. (`openssl req -new -key your.key -out your.csr`)
- Sign that Certificate Request to obtain a Certificate, with your same private key. (`openssl x509 -req -days 365 -in your.csr -signkey your.key -out your.crt`)

Note that in the example I gave, I added `-days 365` because having a certificate that only lasts a month is annoying, especially when you are using a self-signed one. Feel free to extend that duration, as long as you understand the security risks of doing so.

I also found [that question](http://superuser.com/questions/622434/can-self-signed-ssl-certificate-be-renewed-how) that can probably help.

I'm closing this issue as it is not really a FreeLAN-specific issue. Feel free to comment though.

**Comment by chrisidefix** [comment]
Thanks, I was able to create a new certificate, but didn't get it to work with that after all. I now get these messages:
```
09/03/16 06:25:16.264 freelan[759]: Error when validating [...]: unable to get local issuer certificate (depth: 0)
09/03/16 06:25:16.264 freelan[759]: Ignoring PRESENTATION from [IP]:[PORT] as the signature certificate is invalid.
```

Would I have to sign each of the existing client certificates with this new certificate (again) before I can use this new certificate or should it work with the existing (already deployed) client certificates?

**Comment by chrisidefix** [comment]
Ok, so I also created a new certificate request for the client and signed it. It works now, but I am still wondering if this is the expected procedure or if the older signed client certificate (that was still valid) should technically still have worked?

If I would want to have a "short" life-span of certificates, which appears to be preferred, do I continuously have to re-sign all clients or should their certificates remain intact once I update the `ca.crt` ?

(Note that I didn't have / want to change any private keys here.)

**Comment by ereOn** [comment]
You have two things to consider here:

- The CA certificate, which is usually self-signed and trusted, which is used along with its private key to sign other, client certificates. This certificate usually has an extended validity period, which can be several years (because when it becomes invalid, you have to resign the client certificates). Obviously, the private key for this certificate has to be stored securely and carefuly guarded. Storing it offline is a very good idea.
- The client certificates which are not self-signed, and have a smaller validity period (a year is common practice but your mileage may vary). The process is usually for clients to issue a Certificate Request (using their private key, which does not need to change, ever, unless its compromised) and to send that CSR to the Certification Authority. The CA signs the client CSR to generate a Client Certificate that your client can use. This is when the validity period is decided (by the CA).

Does that make sense ?

**Comment by chrisidefix** [comment]
Yes, this absolutely makes sense and I think so far I did understood the process as you describe it.

What I was / am unsure about is if I absolutely have to resign the client certificates, as you said, once the main CA certificate expires. When I generate a renewed CA certificate **from the same private key** - according to the accepted answer in this post, I was wondering if resigning the client certificates wouldn't be required:
http://serverfault.com/questions/306345/certification-authority-root-certificate-expiry-and-renewal

> Keeping the same private key on your root CA allows for all certificates to continue to validate successfully against the new root; all that's required of you is to trust the new root.
> 
> The certificate signing relationship is based on a signature from the private key; keeping the same private key (and, implicitly, the same public key) while generating a new public certificate, with a new validity period and any other new attributes changed as needed, keeps the trust relationship in place. CRLs, too, can continue over from the old cert to the new, as they are, like certificates, signed by the private key.
