### ISSUE TITLE
Freelan mangling paths in config

### ISSUE THREAD

**Issue by retep998** [freelan-developers/freelan#107]
Windows 10 64-bit using the version of FreeLAN from the website (1.1)
I have freelan installed to "C:\Program Files\FreeLAN".
The config is at the default location of "C:\Program Files\FreeLAN\config\freelan.cfg"
I have the following line in my config: `authority_certificate_file="D:\foo\bar\ca.crt"`
Upon attempting to run freelan I get this error: `Error: No such file: "D:\Program Files\FreeLAN\bin\foo\bar\ca.crt"`

EDIT: Freelan 2.0 fixes this. Why does the website still only offer 1.1 for download?

**Comment by ereOn** [comment]
@retep998 I recently sadly had to dramatically reduce my amount of contribution to open-source software due to personal reasons. This lack of time prevented me from updating the website.

You may find the most recent version for Windows [here](https://github.com/freelan-developers/freelan/releases/tag/2.0). Sorry for the confusion.
