### ISSUE TITLE
Change default IPv4 address

### ISSUE THREAD

**Issue by albocc** [freelan-developers/freelan#123]
According to the `README` the default configuration of freelan is to pick the 9.0.0.1 IPv4 address for inside the emulated network:
> The node will pick the default 9.0.0.1 IPv4 address inside the emulated network.

This should be changed since the 9.0.0.0/8 network [is not a private address space](https://www.iana.org/assignments/ipv4-address-space/ipv4-address-space.xhtml) and therefore might be used for actual internet servers. If a client attempts to access a resource on that network, it will not be able to reach it while having the VPN network established, since all the traffic to it is considered internal traffic. While this might be okay if the nodes do not need to access any resource on the internet, in most scenarios this is not desirable. 

Instead, freelan should be using one of the [reserved private address](https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml) spaces like 10.0.0.0/8 or 172.16.0.0/12 or 192.168.0.0/16.

**Comment by ereOn** [comment]
@albocc This decision was actually made to avoid conflicts as much as possible.

Having the virtual private network reuse a private network (like the ones you mention) causes conflicts in most personnal and sometimes professional setups as you can't usually have two different network card in the same network.

The decision to use 9.0.0.0 (which is an IBM-allocated address space) was made because in practice this range shouldn't be used for public addresses. The same logic applies for 5.0.0.0 which is currently used by Hamachi (a concurrent VPN software). Put otherwise: practicality beats purity.

**Comment by PF4Public** [comment]
Hi, Captain Obvious from the future here.

One _should not_ make any assumptions about potential usage or non-usage of the address space outside of Private Address Space. This assumption actually _did_ backfire on Hamachi when IP addresses from the network 5.0.0.0 were <s>suddenly</s> allocated.

I would strongly suggest changing the default IP address and updating the documentation.

**Comment by albocc** [comment]
I don't quite understand it to this day. We are talking about the _default_ network here. If it conflicts with some existing network then simply _change it from the default_.

Personally, in my experience, most networks I encounter use either the 10/8 or the 192.168/16 range, so defaulting to 172.16/12 would be a safe and useful default. It's what Docker uses for similar reasons.

Cc @ereOn

**Comment by ereOn** [comment]
@PF4Public @albocc 

It's important to consider things in their context otherwise it's easy to arrive at incorrect conclusions. Choosing one of those networks seems obvious, but still it wasn't done. Could it be there is a rationale behind that choice? 

`9.0.0.0/8` is (or was?) not used at the time of the decision, just like `5.0.0.0` wasn't either. It was now some *years* ago that this decision was made and things may - or may not - have changed since then. I couldn't possibly know.

The project started with the `10/8` then `192.168/16` and finally `172.16/12` ranges as a default. This proved to be a terrible decision in each and every case because there was always someone else complaining that the `default` address was conflicting with their particular home, work or university network. Docker has it easy: you only need to ensure the lack of conflicts locally. A VPN network has to consider ALL the VPN-nodes which may each have their own networks and IP-ranges. Here lies a rather important difference.

In that sense, picking `9.0.0.0/8` although it was theoretically not a good choice, proved to be a particular practical one and did actually solve the biggest problem at the time: avoiding the *many*, *many* complaints about silly conflicting configuration issues for a value that can actually be changed pretty easily. See it as a tradeoff: annoying a few, likely non-existing, IBM employees or the vast majority of the casual users. I suspect Hamachi had the same rationale. Now some purists might not like that, but sometimes reality has a naughty way of making theory fail spectacularly. This is one of those cases.

This is an open-source project that has, for a long time, been maintained by a single person (me). Whatever decision I could take to alleviate the burden of the never ceasing complaints and expressed dissatisfaction - for something that was provided to users at *absolutely zero cost*, I should add - I did. And as you rightfully mention, this is only a *default* value luckily, so it's not like any default would really cause unfixable issues. If it is mostly a philosophical problem, I shall leave it to the philosophers.

We could also sum it up that way: In the absence of a good and perfect default that causes minimal complaints, I had to pick the less terrible solution.

Remember: you guys are not affected by the support requests, I am. And I get *absolutely nothing* from all this effort (except the occasional "it's obvious! you should have done it that way! Duh!" comment which is always really appreciated...).

**Comment by PF4Public** [comment]
@ereOn, thank you for your quick reply and thanks for sharing your thoughts on the topic!

First of all I do understand your frustration with people complaining about something they get for free. As a matter of fact I do maintain some projects (one can see them in my profile overview if curious) and also get tons of complaints and "smart" suggestions. At the beginning I was really frustrated, but later I came to realising that I owe nothing to anyone and the frustration is gone.

You bring good reasoning for default IP being the way it is now. 

And I could probably make my point more clear from the start. I do agree that Private ranges are not used uniformly throughout internet and it could come to the situation where 3 connecting clients each belong to different net and it would be ultimately impossible to use any of them. But frankly speaking such situation must be very rare and in my opinion 172 network is usually neglected more than others. @albocc seems to agree with that. Using any public IP range would be a good choise for, say Hamachi, but unlike Hamachi freelan is intended to be configured before the first run. Which means that a user should decide which network suits best all clients.

So my points are: 
* Documentation does not mention the downsides of using 9.0.0.0 subnet (it might have none today, but what about tomorrow?)
* Documentation does not mention that there are networks guaranteed to not have those downsides and are therefore more recommended for usage
* If there would be such information in the documentation it would be fairly logical to make 172 a default network with clear instructions for checking whether it is suited or not and if the latter is the case an advice on changing it

Apart from that I do not fully understand the need to cater for all the "silly configurations" and "complaints". This software is supposed to be manually configured → user reads the docs → user configures it in accordance with one's needs → bam it works. If user cannot read documentation for this software, user should try another software, which works automatically. And if someone complains — it's their fault.
 
Now with all that being said I do realise the software is no longer being maintained, so nothing likely will change and our discussion indeed becomes purely philosophical in nature.

Sorry for starting this.
