### ISSUE TITLE
[RFE] Vcpkg to build/use Windows dependencies

### ISSUE THREAD

**Issue by s-vincent** [freelan-developers/freelan#175]
FreeLAN has some dependencies (Boost, OpenSSL, CuRL, MiniUPNPC). On GNU/Linux and macOS systems, we use their package managers (apt-get/yum and brew) to install these ones. On Windows, we rely on teapot which is a Python2 executable and we update ourself the dependencies version, compiler flags in a .party file. That is a bit difficult for maintenance IMHO because it a library has a vulnerabilities and developer do not react quickly, people still build FreeLAN without outdated libraries.

I propose to switch on [vcpkg](https://github.com/Microsoft/vcpkg) utility. It manages dependencies, compilation, global installation so that multiple projects can benefit of libraries. It can reduce maintenance of the Windows dependencies for us and use a more "standard" Windows utility to do that.

@freelan-developers/developers WDYT ?

**Comment by ereOn** [comment]
Seems good to me.We are currently relying on custom tools for this but those are hardly maintained. Le 28 août 2018 13 h 38, Sebastien Vincent <notifications@github.com> a écrit :FreeLAN has some dependencies (Boost, OpenSSL, CuRL, MiniUPNPC). On GNU/Linux and macOS systems, we use their package managers (apt-get/yum and brew) to install these ones. On Windows, we rely on teapot which is a Python2 executable and we update ourself the dependencies version, compiler flags in a .party file. That is a bit difficult for maintenance IMHO because it a library has a vulnerabilities and developer do not react quickly, people still build FreeLAN without outdated libraries.
I propose to switch on vcpkg utility. It manages dependencies, compilation, global installation so that multiple projects can benefit of libraries. It can reduce maintenance of the Windows dependencies for us and use a more "standard" Windows utility to do that.
@freelan-developers/developers WDYT ?

**Comment by s-vincent** [comment]
I pushed [vcpkg branch](https://github.com/freelan-developers/freelan/tree/vcpkg) to track changes.

Feel free to test it!

**Comment by s-vincent** [comment]
In this branch, I enabled UPnP by default for Windows. Appveyor builds also run fine for the matrix x64/x86/Release/Debug.

**Comment by s-vincent** [comment]
See PR #178.

**Comment by s-vincent** [comment]
PR #181 is pending to be merged in this PR.

After that, I believe it will be safe to merge this branch into master.

**Comment by s-vincent** [comment]
Branch merged.
