### ISSUE TITLE
init script in Debian 9 - little bug

### ISSUE THREAD

**Issue by ds2k5** [freelan-developers/freelan#189]
Hi, 
the initscript for Debian 9 is wrong:

/usr/sbin/freelan  but it is in /bin/freelan

and the /etc/default/freelan search for /etc/freelan/freelan.conf but the file is freelan.cfg

**Comment by 21h** [comment]
I confirm it

**Comment by s-vincent** [comment]
@leggewie related to Debian packaging.

If you can look at that when you have some time. Thanks.

**Comment by lonerzzz** [comment]
I did not see the init.d code for the Debian distro in this repo. Does anyone know where the Debian distribution code is maintained?

**Comment by havardAasen** [comment]
Rolf Leggewie orphaned the package in debian early 2018 so you might not get a response from him.

> /usr/sbin/freelan but it is in /bin/freelan

was fixed in debian release 2.0-8 which came out in 2018

> and the /etc/default/freelan search for /etc/freelan/freelan.conf but the file is freelan.cfg

was fixed in debian release 2.2-2 which migrated to testing today
It's unlikely that these changes gets backported to stretch.

@lonerzzz 
As for the debian repo, this might be what you are looking for
[https://salsa.debian.org/debian/freelan](url)
