### ISSUE TITLE
Example of Full Mesh Typology.

### ISSUE THREAD

**Issue by ndo360** [freelan-developers/freelan#205]
Greetings!

I am presently struggling on figuring out how to configure a full mesh typology with FreeLAN. All the examples provided, at least from what I have seen, have suggested more of a 'Client / Server' approach. What am I missing, and how can I configure a full mesh. Could someone kindly provide an example between three nodes?

Cheers,
Noah C. Cline

**Comment by richman1000000** [comment]
Hello!
freelan supports Peer-to-Peer connect (not torrent connection) which means, useful data can go from one **white ip** to another.

One of the peers , the one with **White IP** maybe need as a point of metadata exchange for Dynamic contacts.
Dynamic Contact needed if your client machines behind NAT.

But as a whole freelan supports Hybrid topology. There were sort of Metatada server (https://github.com/freelan-developers/freelan-server) in freelan1.1 but they removed it due to license issues.
I hope Developers of Freelan will revive it

**Comment by ndo360** [comment]
Thanks for the reply, please forgive my ignorance, but does this mean that a full mesh network isn't possible?

The reason I ask is the site says it should be supported, and the diagram it shows gives the impression that there wouldn't be a single point of failure. 

The ports can be forwarded for all clients if that resolves NAT problems, just trying to make sure I understand. Apologies for my ignorance on this, first time trying to do something involving this program.

P.S. White IP... Is that the one that starts the network? Has connection to the internet with ports forwarded?

**Comment by ndo360** [comment]
Also, apoligies if I have misused the term 'full mesh'. I was trying to ask how to create the P2P network that doesn't have a single point of failure.

**Comment by richman1000000** [comment]
freelan can make full-mesh for **data traffic** WITHOUT port forwarding. I've tested this part.
However you need a server for meta-data.

In my installation I had:
- 1,5 Mbit Server with White IP 
- 10 clients with speed 100 Mbits.
(Due to Providers Market, Enterprise connection much slower and yet 4-10 times more expensive )

I need network backup, and freelan was a perfect solution. 👍 
backups were flowing at speed 40-50 mbits between clients. One of  clients was a storage.

**Comment by richman1000000** [comment]
unfortunately freelan doesn't support  distributed hash table (DHT)

**Comment by ndo360** [comment]
So there would always be a single point of failure then? As I presume meta-data must be resolved for the network to function.

**Comment by richman1000000** [comment]
not exactly.
Any peer with WhiteIP can accept meta-data request and forward them, thus anyone with WhiteIP  can become a server.
This is done manually currently (you have to posted you IP info somewhere)
But DHT just automates this part, I think.

**Comment by ndo360** [comment]
Could FreeLAN support multiple 'White IPs?' (Tinc has a similar system, but the mesh keeps track of the hosts and can tell who is portforwarxed and able to transfer meta-data.)

**Comment by richman1000000** [comment]
yes, it is

**Comment by ndo360** [comment]
Could you write an example where this is possible?

**Comment by ndo360** [comment]
Okay after reading the config file more closely, I noticed that there is a method to get users contact information. (You have to use certificates, accept contacts, and the sort.)

My one question now is the 'dynamic_contact_file' by default is empty. If it's empty, will a list of contacts still be compiled, if not how would I specify a file? Cheers!
