### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by allywilson** [freelan-developers/freelan#243]
Last commit almost 2 years ago. Not seeing issues being closed either.

**Comment by ereOn** [comment]
Original author here.

There was a soft hand-off of the project done a couple of years ago to a friend of mine that was involved in development from day 1.

The project is not dead, but to be fair it's not really alive either.

It is a bit hard to dedicate so much time on something, not getting much in return and sometimes get insulted because the free software people got didn't exactly match their expectations. This and the amount of support, complaints and otherwise lack of personal time got the better of my motivation to continue maintaining it on a regular basis.

**Comment by allywilson** [comment]
I fully understand, and appreciated your points. Hope you, or someone else, has the ability and patience to pick it up again in the future.

Thank you for your hard work.
