### ISSUE TITLE
HTTP client sometimes hangs on Windows

### ISSUE THREAD

**Issue by ereOn** [freelan-developers/freelan#48]
The client gets stuck and also prevents the app from shuting down.

**Comment by s-vincent** [comment]
What is the state of this issue ? Do the commit 77e5ba1 fixed it ?

**Comment by ereOn** [comment]
I don't think so. It's been a while since I worked on that. I have no memories on the context sadly.

**Comment by s-vincent** [comment]
@ereOn I believe it is fixed with 11518d0ad22394b3b38bf36bad05c01ea5eee787.

Here is the scenario I have reproduce:
 * launch freelan;
 * wait just time to send the client web request;
 * stop application;
 * application hangs.

I guess it is because at one moment we may recreate fscp::server object that blocks application to completely shutdown.

I close the ticket from now. Feel free to reopen if any.
