### ISSUE TITLE
.md mark-up in releases

### ISSUE THREAD

**Issue by leggewie** [freelan-developers/freelan#80]
The Markdown files are hard to read outside of github.  And the very long lines don't help.  Is it possible to some more sane format during the build or release?

**Comment by ereOn** [comment]
Actually, my choice of Markdown is not because of Github: it's because I believe it to be a very nice raw format for writing textual docs. The fact that Github displays it nicely is only a bonus.

My editor has line-wrapping enabled so the long lines are not really an issue for me but I can understand how a different setting might cause a different opinion.

I don't might limiting the length of lines to 79 characters (a common-standard I believe) but could you tell me which files you noticed were containing lines that are too long ?

**Comment by s-vincent** [comment]
@leggewie @ereOn A possibility could be to generate a plain-text with pandoc during the packaging state:
`pandoc -f markdown -t plain --wrap=auto --columns=80 README.md -o README`

**Comment by leggewie** [comment]
While I am generally a fan of plaintext files, I'm afraid that with the original author using rich text there will be a loss of information, more importantly one that the original author may not take into account at the time of writing, resulting in confusing plaintext docs.

In the end, this is really a nitpick.

**Comment by s-vincent** [comment]
In a93f3c1baf5544848168cdb3cc639092f0ba8c82 I wraps to 80 columns line so that we have something more "standard".

I close the issue. Feel free to reopen if any.

**Comment by leggewie** [comment]
JFTR, I am using the retext program to read markdown files nowadays.  That actually makes markdown shine and has changed my markdown-allergy to markdown-enthusiasm.  Still looking for a command-line markdown-reader.  And [pandoc might just be ticket for that](https://unix.stackexchange.com/questions/4140/markdown-viewer).
