### ISSUE TITLE
Dynamic Contact Server IP

### ISSUE THREAD

**Issue by Tr4at** [freelan-developers/freelan#97]
Hi,

First of all very good job on this project :)

Quick question tho, lets say i have several clients connecting to 1 server but the server's public ip is dynamic so it changes all the time..., is there any easier way to adjust to this situation other than changing the contact ip address in the config file under each client manually?

**Comment by ereOn** [comment]
@Tr4at This is the exact problem solved by DNS names.

It is actually not directly related to FreeLAN: you basically create an named alias that will be resolved later as the actual server's IP address. So instead of putting the raw IP address in the configuration file, you just write down the named alias. This is BTW exactly what happens when you browse on Github for instance: the name `github.com` is resolved to the server's IP address and then your web browser uses that address to send its requests.

There are free DNS names providers out there. I'd recommend [`no-ip`](http://www.noip.com/) which is free and good. You may use another one.

Closing this issue as it's really a FreeLAN related problem.
